
person:               anton

name:               "hipster science minimal working examples digest by @alexeyev"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
gems:
- jekyll-mentions

highlighter: pygments
markdown: redcarpet
extensions: [fenced_code_blocks]
